package com.outr.robobrowser.appium

case class BundleId(id: String)

object BundleId {
  lazy val AppStore: BundleId = BundleId("com.apple.AppStore")
  lazy val AppleStore: BundleId = BundleId("com.apple.store.Jolly")
  lazy val Books: BundleId = BundleId("com.apple.iBooks")
  lazy val Calculator: BundleId = BundleId("com.apple.calculator")
  lazy val Calendar: BundleId = BundleId("com.apple.mobilecal")
  lazy val Camera: BundleId = BundleId("com.apple.camera")
  lazy val Clips: BundleId = BundleId("com.apple.clips")
  lazy val Clock: BundleId = BundleId("com.apple.mobiletimer")
  lazy val Compass: BundleId = BundleId("com.apple.compass")
  lazy val Contacts: BundleId = BundleId("com.apple.MobileAddressBook")
  lazy val FaceTime: BundleId = BundleId("com.apple.facetime")
  lazy val Files: BundleId = BundleId("com.apple.DocumentsApp")
  lazy val FindMy: BundleId = BundleId("com.apple.findymy")
  lazy val Fitness: BundleId = BundleId("com.apple.Fitness")
  lazy val GarageBand: BundleId = BundleId("com.apple.mobilegarageband")
  lazy val Health: BundleId = BundleId("com.apple.Health")
  lazy val Home: BundleId = BundleId("com.apple.Home")
  lazy val iCloudDrive: BundleId = BundleId("com.apple.iCloudDriveApp")
  lazy val iMovie: BundleId = BundleId("com.apple.iMovie")
  lazy val iTunesStore: BundleId = BundleId("com.apple.MobileStore")
  lazy val Keynote: BundleId = BundleId("com.apple.Keynote")
  lazy val Magnifier: BundleId = BundleId("com.Apple.Magnifier")
  lazy val Mail: BundleId = BundleId("com.apple.mobilemail")
  lazy val Maps: BundleId = BundleId("com.apple.Maps")
  lazy val Measure: BundleId = BundleId("com.apple.measure")
  lazy val Messages: BundleId = BundleId("com.apple.MobileSMS")
  lazy val Music: BundleId = BundleId("com.apple.Music")
  lazy val News: BundleId = BundleId("com.apple.news")
  lazy val Notes: BundleId = BundleId("com.apple.mobilenotes")
  lazy val Numbers: BundleId = BundleId("com.apple.Numbers")
  lazy val Pages: BundleId = BundleId("com.apple.Pages")
  lazy val Phone: BundleId = BundleId("com.apple.mobilephone")
  lazy val PhotoBooth: BundleId = BundleId("com.apple.Photo-Booth")
  lazy val Photos: BundleId = BundleId("com.apple.mobileslideshow")
  lazy val Podcasts: BundleId = BundleId("com.apple.podcasts")
  lazy val Reminders: BundleId = BundleId("com.apple.reminders")
  lazy val Safari: BundleId = BundleId("com.apple.mobilesafari")
  lazy val Settings: BundleId = BundleId("com.apple.Preferences")
  lazy val Shortcuts: BundleId = BundleId("com.apple.shortcuts")
  lazy val Stocks: BundleId = BundleId("com.apple.stocks")
  lazy val SwiftPlaygrounds: BundleId = BundleId("com.apple.Playgrounds")
  lazy val Tips: BundleId = BundleId("com.apple.tips")
  lazy val Translate: BundleId = BundleId("com.apple.Translate")
  lazy val TV: BundleId = BundleId("com.apple.tv")
  lazy val VoiceMemos: BundleId = BundleId("com.apple.VoiceMemos")
  lazy val Wallet: BundleId = BundleId("com.apple.Passbook")
  lazy val Watch: BundleId = BundleId("com.apple.Bridge")
  lazy val Weather: BundleId = BundleId("com.apple.weather")
}